import { DM_Mono } from "next/font/google"
import "./globals.css";

const dm_mono = DM_Mono({
  weight: ['400','500'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dm_mono.className}>
      <body>{children}</body>
    </html>
  )
}
