import { DM_Mono } from "next/font/google"
import { IBM_Plex_Sans_Thai } from "next/font/google"
import "./globals.css";

const dm_mono = DM_Mono({
  weight: ['400','500'],
  subsets: ['latin'],
  display: 'swap',
})

const ibm_plex_sans_thai = IBM_Plex_Sans_Thai({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'thai'],
  display: 'swap',
  variable: '--font-ibm-plex-sans-thai',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dm_mono.className} ${ibm_plex_sans_thai.variable}`}>
      <body>{children}</body>
    </html>
  )
}